name: Filter targeted file changes

on: 
  pull_request:
    types: 
      - ready_for_review
      - synchronize
    paths:
      - 'track_file_changes.md'

jobs:
  filter-file-changes:
    name: Detect specific file changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get changes in specific file
      id: changed-files
        uses: tj-actions/changed-files@v35
        with: 
          files: track_file_changes.md
      - name: Run step if file changes detected in previous step
        if: steps.changed-files.outputs.any_changed == 'true'
        run: 
          echo "Changes have been detected in your targeted file"
          echo "Confirming change in your targeted file: ${{steps.changed-file.outputs.all_changed_files}}"

